In [1]:
import pandas as pd 
import numpy as np
import os
import sqlalchemy

In [2]:
beneficiary_file = "Test_Beneficiarydata-1542969243754.csv"
beneficary_df = pd.read_csv(beneficiary_file)
beneficary_df.head()

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaN,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11007,1940-09-01,2009-12-01,1,2,0,45,610,12,12,...,2,1,2,1,1,2,0,0,1490,160
2,BENE11010,1936-07-01,NaN,2,1,0,41,30,12,12,...,2,1,1,1,2,2,0,0,1170,660
3,BENE11011,1914-03-01,NaN,2,2,0,1,360,12,12,...,1,1,2,2,1,1,5000,1068,250,320
4,BENE11014,1938-04-01,NaN,2,1,Y,45,780,12,12,...,1,2,1,2,2,2,21260,2136,120,100

In [3]:
beneficary_df.columns

Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
       'State', 'County', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt'],
      dtype='object')

In [4]:
beneficary_df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
BeneID,63968,63968,BENE127949,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOB,63968,900,1940-03-01,265,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOD,574,12,2009-12-01,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,63968,NaN,NaN,NaN,1.57405,0.49449,1,1,2,2,2
Race,63968,NaN,NaN,NaN,1.25022,0.710366,1,1,1,1,5
RenalDiseaseIndicator,63968,2,0,53408,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,63968,NaN,NaN,NaN,26.2987,14.9541,1,12,26,39,54
County,63968,NaN,NaN,NaN,368.598,270.244,0,140,330,560,999
NoOfMonths_PartACov,63968,NaN,NaN,NaN,11.9189,0.967169,0,12,12,12,12
NoOfMonths_PartBCov,63968,NaN,NaN,NaN,11.9282,0.841754,0,12,12,12,12
ChronicCond_Alzheimer,63968,NaN,NaN,NaN,1.63257,0.48211,1,1,2,2,2
ChronicCond_Heartfailure,63968,NaN,NaN,NaN,1.45745,0.49819,1,1,1,2,2
ChronicCond_KidneyDisease,63968,NaN,NaN,NaN,1.6391,0.480265,1,1,2,2,2
ChronicCond_Cancer,63968,NaN,NaN,NaN,1.86256,0.344318,1,2,2,2,2
ChronicCond_ObstrPulmonary,63968,NaN,NaN,NaN,1.7261,0.445963,1,1,2,2,2
ChronicCond_Depression,63968,NaN,NaN,NaN,1.60707,0.488405,1,1,2,2,2
ChronicCond_Diabetes,63968,NaN,NaN,NaN,1.34677,0.475945,1,1,1,2,2
ChronicCond_IschemicHeart,63968,NaN,NaN,NaN,1.28267,0.450302,1,1,1,2,2
ChronicCond_Osteoporasis,63968,NaN,NaN,NaN,1.70406,0.45647,1,1,2,2,2
ChronicCond_rheumatoidarthritis,63968,NaN,NaN,NaN,1.71769,0.450128,1,1,2,2,2
ChronicCond_stroke,63968,NaN,NaN,NaN,1.90953,0.286852,1,2,2,2,2
IPAnnualReimbursementAmt,63968,NaN,NaN,NaN,4557.56,10742,-1000,0,0,5000,155600
IPAnnualDeductibleAmt,63968,NaN,NaN,NaN,497.288,1095.43,0,0,0,1068,38272
OPAnnualReimbursementAmt,63968,NaN,NaN,NaN,1664.71,3010.05,-60,290,800,1960,97510
OPAnnualDeductibleAmt,63968,NaN,NaN,NaN,478.964,768.234,0,70,230,590,13840

In [5]:
inpatient_file = "Test_Inpatientdata-1542969243754.csv"
inpatient_df = pd.read_csv(inpatient_file)
inpatient_df.head(100)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11014,CLM67387,2009-09-09,2009-09-16,PRV57070,9000,PHY317786,PHY427017,NaN,2009-09-09,...,5990,570,41071,4280,4443.0,5849.0,NaN,NaN,NaN,NaN
1,BENE11017,CLM31237,2008-12-25,2009-01-08,PRV54750,14000,PHY314656,PHY426644,NaN,2008-12-25,...,4549,29570,34831,NaN,5551.0,NaN,NaN,NaN,NaN,NaN
2,BENE11026,CLM78930,2009-12-09,2009-12-13,PRV53758,2000,PHY349495,NaN,NaN,2009-12-09,...,78650,7813,4254,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11031,CLM56810,2009-06-23,2009-07-06,PRV55825,16000,PHY429538,PHY371893,NaN,2009-06-23,...,4254,41400,5849,41401,8152.0,3320.0,NaN,NaN,NaN,NaN
4,BENE11085,CLM34625,2009-01-20,2009-01-31,PRV52338,19000,PHY397161,NaN,NaN,2009-01-20,...,V6109,7242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,BENE12512,CLM76961,2009-11-23,2009-11-27,PRV55380,10000,PHY404690,NaN,PHY404690,2009-11-23,...,5990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,BENE12514,CLM56223,2009-06-19,2009-06-20,PRV54948,6000,PHY366268,PHY366268,NaN,2009-06-19,...,28860,4928,NaN,NaN,3723.0,NaN,NaN,NaN,NaN,NaN
97,BENE12531,CLM69230,2009-09-23,2009-10-06,PRV53275,16000,PHY425441,PHY389026,NaN,2009-09-23,...,NaN,NaN,NaN,NaN,9322.0,311.0,NaN,NaN,NaN,NaN
98,BENE12584,CLM80384,2009-12-22,2009-12-24,PRV51597,5000,PHY367336,PHY431486,NaN,2009-12-22,...,41401,2948,2720,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,BENE12585,CLM57816,2009-06-30,2009-07-02,PRV52655,5000,PHY378358,PHY330052,NaN,2009-06-30,...,2859,V5489,5690,NaN,4525.0,NaN,NaN,NaN,NaN,NaN

In [69]:
outpatient_file = "Test_Outpatientdata-1542969243754.csv"
outpatient_df = pd.read_csv(outpatient_file)
outpatient_df.head(10)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11001,CLM392397,2009-06-02,2009-06-02,PRV55962,30,PHY347633,NaN,PHY347633,V5832,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
1,BENE11001,CLM430760,2009-06-23,2009-06-23,PRV56112,30,PHY381777,NaN,PHY381777,9594,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
2,BENE11007,CLM233081,2009-03-07,2009-03-07,PRV56979,200,PHY425311,NaN,PHY425311,7248,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,BENE11007,CLM496381,2009-07-29,2009-07-29,PRV56573,10,PHY393253,PHY347995,NaN,58889,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5939
4,BENE11007,CLM521391,2009-08-12,2009-08-12,PRV56573,10,PHY417685,NaN,PHY382041,V666,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
5,BENE11007,CLM537365,2009-08-21,2009-08-21,PRV56612,600,PHY433586,NaN,PHY334391,8409,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
6,BENE11007,CLM646966,2009-10-24,2009-10-24,PRV56678,50,PHY396806,NaN,PHY404886,4011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
7,BENE11007,CLM689394,2009-11-19,2009-11-19,PRV56565,50,PHY386663,NaN,PHY431113,4019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,4019
8,BENE11010,CLM140012,2009-01-16,2009-01-16,PRV56204,20,PHY371583,NaN,PHY371583,4111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
9,BENE11010,CLM165765,2009-01-30,2009-01-30,PRV56204,70,PHY314960,NaN,NaN,V777,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [70]:
provider_file = "Test-1542969243754.csv"
provider_df = pd.read_csv(provider_file)
provider_df.head(100)

    Provider
0   PRV51002
1   PRV51006
2   PRV51009
3   PRV51010
4   PRV51018
..       ...
95  PRV51461
96  PRV51463
97  PRV51473
98  PRV51481
99  PRV51485

[100 rows x 1 columns]

In [71]:
test_data1 = pd.merge(inpatient_df, outpatient_df, how='outer')
test_data1.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11014,CLM67387,2009-09-09,2009-09-16,PRV57070,9000,PHY317786,PHY427017,NaN,2009-09-09,...,5990,570,41071,4280,4443.0,5849.0,NaN,NaN,NaN,NaN
1,BENE11017,CLM31237,2008-12-25,2009-01-08,PRV54750,14000,PHY314656,PHY426644,NaN,2008-12-25,...,4549,29570,34831,NaN,5551.0,NaN,NaN,NaN,NaN,NaN
2,BENE11026,CLM78930,2009-12-09,2009-12-13,PRV53758,2000,PHY349495,NaN,NaN,2009-12-09,...,78650,7813,4254,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11031,CLM56810,2009-06-23,2009-07-06,PRV55825,16000,PHY429538,PHY371893,NaN,2009-06-23,...,4254,41400,5849,41401,8152.0,3320.0,NaN,NaN,NaN,NaN
4,BENE11085,CLM34625,2009-01-20,2009-01-31,PRV52338,19000,PHY397161,NaN,NaN,2009-01-20,...,V6109,7242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
test_data2 = pd.merge(test_data1, beneficary_df, how='outer')
test_data2.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11014,CLM67387,2009-09-09,2009-09-16,PRV57070,9000,PHY317786,PHY427017,NaN,2009-09-09,...,1,2,1,2,2,2,21260,2136,120,100
1,BENE11014,CLM731858,2009-12-16,2009-12-16,PRV56558,60,PHY331420,PHY331420,PHY428520,NaN,...,1,2,1,2,2,2,21260,2136,120,100
2,BENE11017,CLM31237,2008-12-25,2009-01-08,PRV54750,14000,PHY314656,PHY426644,NaN,2008-12-25,...,2,1,1,2,1,1,22000,2136,1400,840
3,BENE11026,CLM78930,2009-12-09,2009-12-13,PRV53758,2000,PHY349495,NaN,NaN,2009-12-09,...,2,2,1,2,2,2,2000,1068,0,0
4,BENE11031,CLM56810,2009-06-23,2009-07-06,PRV55825,16000,PHY429538,PHY371893,NaN,2009-06-23,...,2,2,1,1,2,2,23650,2136,40,0

In [73]:
test_data2.shape

(135392, 54)

In [76]:
test_data2.describe(include=[np.number]).T

,count,mean,std,min,25%,50%,75%,max
InscClaimAmtReimbursed,135392.0,981.307906,3788.177532,0.0,40.00,80.0,300.00,125000.0
DeductibleAmtPaid,135196.0,76.499194,270.779562,0.0,0.00,0.0,0.00,1068.0
ClmProcedureCode_1,5467.0,5905.430766,3057.976988,14.0,3891.00,5369.0,8741.00,9999.0
ClmProcedureCode_2,1263.0,4138.790182,2042.016095,42.0,2749.00,4019.0,4439.00,9998.0
ClmProcedureCode_3,225.0,4182.213333,2165.057828,185.0,2724.00,4019.0,5121.00,9984.0
ClmProcedureCode_4,29.0,4509.931034,2571.379659,260.0,3320.00,4263.0,5781.00,9971.0
ClmProcedureCode_5,2.0,7055.500000,4124.553855,4139.0,5597.25,7055.5,8513.75,9972.0
ClmProcedureCode_6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,135392.0,1.576231,0.494157,1.0,1.00,2.0,2.00,2.0
Race,135392.0,1.240605,0.695578,1.0,1.00,1.0,1.00,5.0
State,135392.0,26.904285,14.651997,1.0,14.00,29.0,39.00,54.0
County,135392.0,373.100375,275.836853,0.0,140.00,330.0,570.00,999.0
NoOfMonths_PartACov,135392.0,11.930469,0.895486,0.0,12.00,12.0,12.00,12.0
NoOfMonths_PartBCov,135392.0,11.943010,0.756944,0.0,12.00,12.0,12.00,12.0
ChronicCond_Alzheimer,135392.0,1.596727,0.490557,1.0,1.00,2.0,2.00,2.0
ChronicCond_Heartfailure,135392.0,1.405504,0.490991,1.0,1.00,1.0,2.00,2.0
ChronicCond_KidneyDisease,135392.0,1.584052,0.492886,1.0,1.00,2.0,2.00,2.0
ChronicCond_Cancer,135392.0,1.845235,0.361682,1.0,2.00,2.0,2.00,2.0
ChronicCond_ObstrPulmonary,135392.0,1.688312,0.463185,1.0,1.00,2.0,2.00,2.0
ChronicCond_Depression,135392.0,1.567463,0.495430,1.0,1.00,2.0,2.00,2.0
ChronicCond_Diabetes,135392.0,1.291745,0.454567,1.0,1.00,1.0,2.00,2.0
ChronicCond_IschemicHeart,135392.0,1.240383,0.427318,1.0,1.00,1.0,1.00,2.0
ChronicCond_Osteoporasis,135392.0,1.683637,0.465058,1.0,1.00,2.0,2.00,2.0
ChronicCond_rheumatoidarthritis,135392.0,1.689923,0.462527,1.0,1.00,2.0,2.00,2.0
ChronicCond_stroke,135392.0,1.895422,0.306010,1.0,2.00,2.0,2.00,2.0
IPAnnualReimbursementAmt,135392.0,5271.108559,11746.248324,-1000.0,0.00,0.0,6000.00,155600.0
IPAnnualDeductibleAmt,135392.0,575.083978,1211.898840,0.0,0.00,0.0,1068.00,38272.0
OPAnnualReimbursementAmt,135392.0,2277.197988,3985.942527,-60.0,470.00,1170.0,2560.00,97510.0
OPAnnualDeductibleAmt,135392.0,645.259572,997.355872,0.0,120.00,340.0,790.00,13840.0

In [79]:
test_data2.describe(include=[np.object])

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,...,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,DOB,DOD,RenalDiseaseIndicator
count,135392,135392,135392,135392,135392,135045,27193,48632,9551,35356,...,39617,26798,20160,15785,12722,9876,1150,135392,1040,135392
unique,63968,135392,392,365,1353,21555,8970,12096,392,2622,...,2817,2475,2181,1947,1792,1577,488,900,12,2
top,BENE103720,CLM719755,2009-04-04,2009-03-29,PRV56573,PHY378872,PHY356259,PHY344080,2009-02-01,V7612,...,4019,4019,4019,4019,4019,4019,4019,1940-12-01,2009-12-01,0
freq,25,1,440,446,3250,939,170,1205,40,997,...,2179,1473,985,707,538,384,47,554,185,109143

In [83]:
test_data2.sample(20)

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
102824,BENE117305,CLM190583,2009-02-12,2009-02-12,PRV52613,80,PHY347833,NaN,NaN,NaN,...,1,1,1,2,2,2,57000,2136,1340,430
129628,BENE151688,CLM591305,2009-09-21,2009-09-21,PRV56678,10,PHY377591,NaN,PHY402141,NaN,...,2,1,2,1,2,2,0,0,120,70
66192,BENE70098,CLM235325,2009-03-08,2009-03-08,PRV54974,30,PHY361392,NaN,NaN,NaN,...,1,1,1,2,2,2,0,0,3470,620
124669,BENE145368,CLM505333,2009-08-03,2009-08-03,PRV54751,50,PHY382619,NaN,NaN,NaN,...,1,1,1,2,2,1,0,0,2690,470
20786,BENE12288,CLM130804,2009-01-11,2009-01-11,PRV52080,900,PHY386115,NaN,NaN,NaN,...,2,1,1,2,1,2,0,0,5080,440
84043,BENE92989,CLM200592,2009-02-17,2009-02-17,PRV56612,90,PHY389970,NaN,PHY334391,NaN,...,2,1,1,2,1,2,0,0,440,230
36647,BENE32552,CLM359733,2009-05-15,2009-05-17,PRV51853,2800,PHY385776,PHY385776,NaN,NaN,...,2,1,1,1,2,2,9060,1068,22620,6660
73940,BENE80061,CLM535156,2009-08-20,2009-08-20,PRV51520,800,PHY339134,PHY423705,NaN,NaN,...,1,1,1,2,2,2,0,0,980,610
102236,BENE116505,CLM694843,2009-11-22,2009-11-22,PRV52083,10,PHY383896,NaN,NaN,NaN,...,2,1,1,2,2,2,5000,1068,3400,1120
105447,BENE120654,CLM129647,2009-01-10,2009-01-10,PRV51939,100,PHY333055,NaN,NaN,NaN,...,1,1,1,1,1,2,17000,1068,840,260
117797,BENE136490,CLM525720,2009-08-14,2009-08-14,PRV57606,200,PHY431379,PHY425325,PHY369630,NaN,...,2,1,1,1,2,1,0,0,600,70
122293,BENE142390,CLM115215,2009-01-02,2009-01-02,PRV55476,100,PHY361734,NaN,NaN,NaN,...,1,1,1,2,1,2,0,0,4450,890
116222,BENE134532,CLM185174,2009-02-09,2009-02-09,PRV57068,500,PHY356870,NaN,NaN,NaN,...,2,2,1,2,2,2,0,0,730,100
97361,BENE110094,CLM554651,2009-08-31,2009-08-31,PRV53852,10,PHY360617,NaN,PHY360617,NaN,...,2,1,1,2,2,2,0,0,810,60
33947,BENE29106,CLM426192,2009-06-20,2009-06-20,PRV55962,50,PHY333010,NaN,PHY347633,NaN,...,2,1,1,2,1,2,0,0,1760,330
97731,BENE110603,CLM627464,2009-10-12,2009-10-12,PRV56678,30,PHY404886,NaN,NaN,NaN,...,1,1,1,1,1,2,0,0,250,20
57198,BENE58755,CLM184650,2009-02-09,2009-02-09,PRV52338,20,PHY326945,NaN,NaN,NaN,...,1,1,1,1,1,2,0,0,620,940
16296,BENE133557,CLM46857,2009-04-13,2009-04-20,PRV53866,9000,PHY329480,NaN,NaN,2009-04-13,...,1,1,2,1,1,2,9000,1068,3360,710
97064,BENE109723,CLM317743,2009-04-22,2009-04-22,PRV54211,0,PHY418859,NaN,PHY418859,NaN,...,2,2,2,1,2,2,0,0,200,20
63231,BENE66252,CLM616313,2009-10-06,2009-10-20,PRV55222,30,PHY317213,NaN,PHY335313,NaN,...,1,1,1,1,1,1,12000,2136,2860,1930

In [95]:
test_data3 = test_data2.drop_duplicates()
test_data3.columns

Index(['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
       'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
       'OtherPhysician', 'AdmissionDt', 'ClmAdmitDiagnosisCode',
       'DeductibleAmtPaid', 'DischargeDt', 'DiagnosisGroupCode',
       'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'ClmDiagnosisCode_3',
       'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5', 'ClmDiagnosisCode_6',
       'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8', 'ClmDiagnosisCode_9',
       'ClmDiagnosisCode_10', 'ClmProcedureCode_1', 'ClmProcedureCode_2',
       'ClmProcedureCode_3', 'ClmProcedureCode_4', 'ClmProcedureCode_5',
       'ClmProcedureCode_6', 'DOB', 'DOD', 'Gender', 'Race',
       'RenalDiseaseIndicator', 'State', 'County', 'NoOfMonths_PartACov',
       'NoOfMonths_PartBCov', 'ChronicCond_Alzheimer',
       'ChronicCond_Heartfailure', 'ChronicCond_KidneyDisease',
       'ChronicCond_Cancer', 'ChronicCond_ObstrPulmonary',
       'ChronicCond_Depression', 'ChronicCond_Diabetes',
       'ChronicCond_IschemicHeart', 'ChronicCond_Osteoporasis',
       'ChronicCond_rheumatoidarthritis', 'ChronicCond_stroke',
       'IPAnnualReimbursementAmt', 'IPAnnualDeductibleAmt',
       'OPAnnualReimbursementAmt', 'OPAnnualDeductibleAmt'],
      dtype='object')

In [100]:
test_data3.nunique()

BeneID                              63968
ClaimID                            135392
ClaimStartDt                          392
ClaimEndDt                            365
Provider                             1353
InscClaimAmtReimbursed                308
AttendingPhysician                  21555
OperatingPhysician                   8970
OtherPhysician                      12096
AdmissionDt                           392
ClmAdmitDiagnosisCode                2622
DeductibleAmtPaid                      15
DischargeDt                           365
DiagnosisGroupCode                    712
ClmDiagnosisCode_1                   8369
ClmDiagnosisCode_2                   3610
ClmDiagnosisCode_3                   3202
ClmDiagnosisCode_4                   2817
ClmDiagnosisCode_5                   2475
ClmDiagnosisCode_6                   2181
ClmDiagnosisCode_7                   1947
ClmDiagnosisCode_8                   1792
ClmDiagnosisCode_9                   1577
ClmDiagnosisCode_10                   488
ClmProcedureCode_1                    659
ClmProcedureCode_2                    170
ClmProcedureCode_3                     68
ClmProcedureCode_4                     20
ClmProcedureCode_5                      2
ClmProcedureCode_6                      0
DOB                                   900
DOD                                    12
Gender                                  2
Race                                    4
RenalDiseaseIndicator                   2
State                                  52
County                                285
NoOfMonths_PartACov                    12
NoOfMonths_PartBCov                    13
ChronicCond_Alzheimer                   2
ChronicCond_Heartfailure                2
ChronicCond_KidneyDisease               2
ChronicCond_Cancer                      2
ChronicCond_ObstrPulmonary              2
ChronicCond_Depression                  2
ChronicCond_Diabetes                    2
ChronicCond_IschemicHeart               2
ChronicCond_Osteoporasis                2
ChronicCond_rheumatoidarthritis         2
ChronicCond_stroke                      2
IPAnnualReimbursementAmt             2383
IPAnnualDeductibleAmt                 132
OPAnnualReimbursementAmt             1840
OPAnnualDeductibleAmt                 747
dtype: int64

In [104]:
test_data3.duplicated(subset=['Provider'])

0         False
1         False
2         False
3         False
4         False
          ...
135387     True
135388     True
135389     True
135390     True
135391     True
Length: 135392, dtype: bool